---
- name: Install mysql databases on new data directory
  command: "mysql_install_db --user=root --ldata={{ mysql_data_dir }}"  

- name: Copy mysql database to new data directory
  command: "cp -Rf /var/lib/mysql/mysql /var/lib/mysql/vagrant/"

- name: Copy user created databases to new data directory
  command: "cp -Rf /var/lib/mysql/{{item.name}} /var/lib/mysql/vagrant/"
  with_items: mysql_databases

- name: Update my.cnf mysql_data_dir
  lineinfile: "dest=/etc/my.cnf regexp=^datadir line='datadir = {{mysql_data_dir}}'"
  notify: restart mysql