# playbook.yml
---
- hosts: all
  vars_files:
    - vars/main.yml
  sudo: true
  roles:    
    - geerlingguy.mysql
    - geerlingguy.apache
    - geerlingguy.php  
    - repos            
    - extra
