# playbook.yml
---
- hosts: all
  vars_files:
    - vars/main.yml
  sudo: true
  roles:
    - repo-webtatic
    - geerlingguy.repo-epel
    - geerlingguy.mysql
    - geerlingguy.apache
    - geerlingguy.php    
    - extra
